### PR TITLE
More SFX

### PR DESCRIPTION
**Pull request by AwfulNasty**
Added the rest of the SFX events. There are some that are unfinished, I didn't assign unfinished events to the bank to make that more clear. Also fixed the credits sequence to match how vanilla handles it.

### CODE REVIEW

**Comment by Raltyro** [comment]
Thank you! i'll review this when i get home
Also wht you mean with the credits sequence?

**Comment by AwfulNasty** [comment]
No problem, mostly the boss sfx (pepperman, vigi, pizzahead) are what's missing now. 

By credits sequence I mean the transition from receding hairline celebration to the golf music, then to the tutorial music and ending with choose the toppings. From opening the master bank in a hex editor, I found that that series is really two separate events, the main credits one, which just plays the first song while also calling the second event, medley, which has the other three.

I also found that fakepeppino has his own audio bus, likely to limit volume based on the clones parameter, which could be useful for volume parity with the final game.

**Comment by Raltyro** [comment]
image
image
:(

**Comment by Raltyro** [comment]
Also how did you know the credits event have 2 seperated events? i need to know how can you do that

**Comment by AwfulNasty** [comment]
Current awful-sfx branch should now have no missing sounds - those were just recordings from in game that I was using to line sounds up. As for the unassigned events, I left those like that in order to make it clear which events were unfinished - I suppose maybe tagging them with unfinished instead might work?

As for how I knew about the two credits, I opened the game's master.strings in a hex editor and extracted this:
[FMOD hex output.txt](https://github.com/Raltyro/Pizza-Tower-fspro-Recreation/files/11530705/FMOD.hex.output.txt)

**Comment by AwfulNasty** [comment]
> Oh yeah if you want to, you can be invited to the collaborators so you can edit the repository

Sure, go ahead and invite me, I'd be glad to help out some more.

**Comment by Raltyro** [comment]
But before i add you in, do you have any other social medias so i can put you to the credits

**Comment by AwfulNasty** [comment]
I don't use social media much, you can link my gamebanana page if you want to (it's also AwfulNasty).

**Comment by Raltyro** [comment]
Alright, i have invited you in, please use the major-sfx branch as of now

**Pull request merged**
